export const PRICE_LIST_REQUEST = "PRICE_LIST_REQUEST";
export const PRICE_LIST_SUCCESS = "PRICE_LIST_SUCCESS";
export const PRICE_LIST_FAIL = "PRICE_LIST_FAIL";

export const PRICE_EDIT_REQUEST = "PRICE_EDIT_REQUEST";
export const PRICE_EDIT_SUCCESS = "PRICE_EDIT_SUCCESS";
export const PRICE_EDIT_FAIL = "PRICE_EDIT_FAIL";